name: Integration Tests

on: [push, pull_request]
jobs:
    test:
      runs-on: ubuntu-latest  # Or self-hosted if you're using a self-hosted runner
      steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Run integration tests
        run: npm test
        env:
          DATABASE_HOST: ${{ secrets.DB_HOST }}
          DATABASE_USER: ${{ secrets.DB_USER }}
          DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DB_NAME }}
  